---
- name: Install pdsh and related packages on CentOS
  ansible.builtin.package:
    name:
      - pdsh
      - pdsh-mod-genders
      - pdsh-rcmd-ssh
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install pdsh on Ubuntu
  ansible.builtin.package:
    name: pdsh
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Generate the genders file
  ansible.builtin.shell: "/usr/bin/aerolab inventory genders > {{ artifacts_dir }}/genders"
  delegate_to: localhost
  run_once: true

- name: Copy the genders file to the nodes
  ansible.builtin.copy:
    src: "{{ artifacts_dir }}/genders"
    dest: /etc/genders
    mode: '0644'
    owner: root
    group: root

- name: Fix /usr permissions
  ansible.builtin.file:
    path: "/usr"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Fix / permissions
  ansible.builtin.file:
    path: "/"
    state: directory
    mode: '0555'
    owner: root
    group: root